### ISSUE TITLE
MFM Sorting 

### ISSUE THREAD

**Issue by jpachuta** [CMU-CREATE-Lab/mfm-issue-tracking#11]
Ts want to be able to sort and pull up messages 

"Currently, have to click into every students’ page to see what message they sent. BUT could there be a way to sort so you’re seeing all messages sent by my student on Tuesday?" Allows for observation of whole class trends and usage (or a student who is different in messaging from other students)
Having to click into every student is also very slow (loading the page is slow and going through the process of choosing every student is slow). Teachers lose motivation to observe student messages.
Seems like they want sorting and grouping to be able to do better analysis.

**Comment by tasota** [comment]
Add option for viewing all student/group messages from a classroom; different windows of time (1 day, 1 week, 1 month?)

Would like to get teacher input on it as well
